#!/bin/sh
#

#read -p "Select the input directory path > " -e INPATH
#read -p "Select the output directory path > " -e OUTPATH

INPATH=/Users/nds_user/working/200131/data/g-iaea-pd-2019
OUTPATH=/Users/nds_user/working/200131/processing

ACE=${OUTPATH}/ace
IOACE=${OUTPATH}/inout-ace

mkdir -p ${ACE} ${IOACE}

ls -1 ${INPATH} |
grep ^g_ |
sed -e "s/g_//" -e "s/[_-]/ /g" -e "s/\.[^.]*$//g" |
sort -k1g > ${OUTPATH}/iso-mat.iaea-g19

while IFS=" " read -r charge elem mass mat
do
    file="${INPATH}/g_${charge}-${elem}-${mass}_${mat}.dat"
    echo
    echo "${file}"
    ln -s "${file}" tape20
    echo 'running njoy for '${elem}${mass}

cat > ${IOACE}/in${elem}${mass} << EOF
moder
20 21/
acer
20 21 0 31 32/
5 1 1/
'Ace ${elem}${mass} IAEA-PD'/
$mat/
stop
EOF
      njoy < ${IOACE}/in${elem}${mass}
      echo 'saving output, pendf, gendf files'
      mv tape31 ${ACE}/${elem}${mass}
      mv tape32 ${ACE}/${elem}${mass}.dir
      mv output ${IOACE}/out${elem}${mass}
      rm tape*
      echo 'finished' ${elem}${mass}

done < ${OUTPATH}/iso-mat.iaea-g19
